### ISSUE TITLE
Type Error breaks trains pages

### ISSUE THREAD

**Issue by 1000000000** [blahblahblah-/goodservice-v2#26]
As of today, the page displaying info on some trains no longer loads for me. Instead I am presented with a solid gray page, and the console outputs the errors included below. This does not affect all trains, and it does not affect page displaying a trains general status (`https://goodservice.io/trains/<train_line>/`), only pages under the level of the train with direction specified (`https://goodservice.io/trains/<train_line>/[NS]/*`). The train lines affected are the 4, 5, A, B, D, N, Q, and SIR. I have gotten this error across three browsers and two systems.  The log is from Firefox.

Encountered on:
* Debian 10.13
   * Mozilla Firefox 102.14.0esr
   * Chromium Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.13 (64-bit)
* iOS 15.7.8
   * DuckDuckGo 7.87.0.0

```
TypeError: n.toReversed is not a function
    o trainModalDirectionPane.jsx:485
    a trainModalDirectionPane.jsx:480
    value trainModalDirectionPane.jsx:477
    value trainModalDirectionPane.jsx:906
    React 8
    unstable_runWithPriority scheduler.production.min.js:291
    React 6
    value trainModal.jsx:57
react-dom.production.min.js:5311:12
    React 5
    unstable_runWithPriority scheduler.production.min.js:291
    React 4
    unstable_runWithPriority scheduler.production.min.js:291
    React 6
    value trainModal.jsx:57
Uncaught (in promise) TypeError: n.toReversed is not a function
    o trainModalDirectionPane.jsx:485
    a trainModalDirectionPane.jsx:480
    value trainModalDirectionPane.jsx:477
    value trainModalDirectionPane.jsx:906
    React 8
    unstable_runWithPriority scheduler.production.min.js:291
    React 6
    value trainModal.jsx:57
trainModalDirectionPane.jsx:485:32
```

**Comment by 1000000000** [comment]
The affected lines do not seem to be entirely consistent. Now they are the 6 and A.

**Comment by blahblahblah-** [comment]
@1000000000 Thanks for reporting this error. Looks like the recent code change added JS code that use Array `.toReversed()`: https://github.com/blahblahblah-/goodservice-v2/commit/6b7282a1c57aaffd27118aee0ec83929008ea7a3#diff-b9e3b555f0b737b75e0eea121aa5fe87316034059686f0ff34782d3144623073R485

This logic only affected train lines that currently have multiple concurrent routings. Regularly that would be the A, but can also include others like the ones you listed.

Anyway, `.toReversed()` isn't supported on older browsers you like yours https://caniuse.com/mdn-javascript_builtins_array_toreversed, and this should be fixed in this commit I made that replaced the use of it. https://github.com/blahblahblah-/goodservice-v2/commit/b1998c844ecf605bf76cde1af784aeac48717cb5

**Comment by 1000000000** [comment]
Everything seems to be working fine since that commit.
